# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmr',
            name='BMR',
            field=models.FloatField(default=0, null=True),
        ),
    ]
